apiVersion: apps/v1
kind: Deployment
metadata:
  name: srert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srert
  template:
    metadata:
      labels:
        app: srert
    spec:
      containers:
      - image: okteto.dev/srert:latest
        name: srert
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d1575643-4126-436f-b32f-0849d83e63ab"
        - name: Vless_Path
          value: "/hktedsvbhtrtsduy"
        - name: Vmess_UUID
          value: "d1575643-4126-436f-b32f-0849d83e63ab"
        - name: Vmess_Path
          value: "/mnvfzawetyghhjd"
        - name: Share_Path
          value: "/v2link"
